name: auto-generate-docs

# Run this workflow every time a new commit pushed to your repository
on:
  pull_request:
    types: [ closed ]
    branches:
      - master

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  docs:
    # Name the Job
    name: auto-generate-docs
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Download doc pr flag
        uses: actions/download-artifact@v2
          with:
            name: doc_flag_pr_${{ github.event.number }}

      # Copy flag to env variable, because there's no early return in workfolws
      - name: Copy flag to GITHUB_ENV
        run: echo "DOCS_CHANGED=$(cat doc_flag_pr_${{ github.event.number }})" >> $GITHUB_ENV

      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        if: env.DOCS_CHANGED == 'true'
        uses: actions/checkout@v2
        with:
          submodules: recursive  # Fetch the Docsy theme
          fetch-depth: 0


      # Sets up node - required by Hugo
      - name: Setup Node
        if: env.DOCS_CHANGED == 'true'
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      # Installs dependencies required by docsy theme
      - name: Install docsy dependencies
        if: env.DOCS_CHANGED == 'true'
        run: |
          cd website
          npm install
          npm build
          sudo npm install -D --save autoprefixer
          sudo npm install -D --save postcss-cli
          cd ../

      # Runs makefile goal - checks changes to /website folder and generates docs
      - name: Run Makefile goal
        if: env.DOCS_CHANGED == 'true'
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make generate-docs

      # Create push request with generated docs
      - name: Create Pull Request
        if: env.DOCS_CHANGED == 'true'
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Auto-updated docs
          branch: docs-generator
          title: Auto-generated docs update
          body: |
            Auto generated docs from PR ${{ github.event.number }}