name: Detect docs changes
on:
  pull_request:
    types: [opened, synchronize, ready_for_review, reopened]
    branches:
      - master
jobs:
  detect-doc-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Detect changes and upload an artifact
        run: |
          git fetch origin master
          git diff origin/master website
          if [[ $(git diff origin/master website) ]]; then
            echo "Changes in docs detected"
            touch ${{ github.event.number }}
            echo "IS_CHANGED=true" >> $GITHUB_ENV
          else
            echo "No changes in docs"
            echo "IS_CHANGED=false" >> $GITHUB_ENV
          fi

      - name: Upload artifact flag
        if: env.IS_CHANGED == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: doc_flag_pr_${{ github.event.number }}
          path: ${{ github.event.number }}

      - name: Remove artifact flag
        if: env.IS_CHANGED != 'true'
        uses: geekyeggo/delete-artifact@v1
        with:
          name: doc_flag_pr_${{ github.event.number }}
          failOnError: false
